name: ezyreach_mobile_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  device_preview: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  firebase_storage: ^12.3.7
  image_picker: ^0.8.7+5
  cached_network_image: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/loginlogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/loginlogo.png
    - assets/coke.jpeg
    - assets/elephanthouse.jpeg
    - assets/unilever.jpeg
    - assets/kandos.jpg
    - assets/munchee.png
    - assets/maliban.jpg
    - assets/shopimg.jpg
    - assets/dashIMG.png
    - assets/slider1.png
    - assets/slider2.png
    - assets/slider3.png
