// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdL_aT_ZCbPgELhOJ2OEa1PrLgZIoNqiM',
    appId: '1:1030152776545:web:71ddb05d31bfd7f4957320',
    messagingSenderId: '1030152776545',
    projectId: 'ezy-reach',
    authDomain: 'ezy-reach.firebaseapp.com',
    storageBucket: 'ezy-reach.firebasestorage.app',
    measurementId: 'G-3QEF2PN8J3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHij9pP2LX5IbK_Rxj_zLTxfxVof1uGLc',
    appId: '1:1030152776545:ios:264c62bd493eef91957320',
    messagingSenderId: '1030152776545',
    projectId: 'ezy-reach',
    storageBucket: 'ezy-reach.firebasestorage.app',
    iosBundleId: 'com.example.ezyreachMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHij9pP2LX5IbK_Rxj_zLTxfxVof1uGLc',
    appId: '1:1030152776545:ios:264c62bd493eef91957320',
    messagingSenderId: '1030152776545',
    projectId: 'ezy-reach',
    storageBucket: 'ezy-reach.firebasestorage.app',
    iosBundleId: 'com.example.ezyreachMobileApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdL_aT_ZCbPgELhOJ2OEa1PrLgZIoNqiM',
    appId: '1:1030152776545:web:c88c93e31cc6f9bd957320',
    messagingSenderId: '1030152776545',
    projectId: 'ezy-reach',
    authDomain: 'ezy-reach.firebaseapp.com',
    storageBucket: 'ezy-reach.firebasestorage.app',
    measurementId: 'G-HS7DKZD4NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMjMFgwrqDZhR6qhlQV2oKU5c-1N9uiEQ',
    appId: '1:1030152776545:android:2ddcaa1869482a41957320',
    messagingSenderId: '1030152776545',
    projectId: 'ezy-reach',
    storageBucket: 'ezy-reach.firebasestorage.app',
  );

}