// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIb1lFY5NkLMja2vnvmv4Q4Wibl2HYzyE',
    appId: '1:51581949561:web:08fcbfe3316f23d46ca6a8',
    messagingSenderId: '51581949561',
    projectId: 'ezyreach-5fe0a',
    authDomain: 'ezyreach-5fe0a.firebaseapp.com',
    storageBucket: 'ezyreach-5fe0a.firebasestorage.app',
    measurementId: 'G-W0B8H1S80S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd8GApOPvXR2SF8MhtL5Mg70jSXEPzDAc',
    appId: '1:51581949561:android:ea8e891318187af76ca6a8',
    messagingSenderId: '51581949561',
    projectId: 'ezyreach-5fe0a',
    storageBucket: 'ezyreach-5fe0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASdscxn5Fe245BWq__754nA8byDs6Zxso',
    appId: '1:51581949561:ios:aaa1b7671b80411c6ca6a8',
    messagingSenderId: '51581949561',
    projectId: 'ezyreach-5fe0a',
    storageBucket: 'ezyreach-5fe0a.firebasestorage.app',
    iosClientId: '51581949561-1g6laijvf65u4174ja22os2adqd6vabo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezyreachMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASdscxn5Fe245BWq__754nA8byDs6Zxso',
    appId: '1:51581949561:ios:aaa1b7671b80411c6ca6a8',
    messagingSenderId: '51581949561',
    projectId: 'ezyreach-5fe0a',
    storageBucket: 'ezyreach-5fe0a.firebasestorage.app',
    iosClientId: '51581949561-1g6laijvf65u4174ja22os2adqd6vabo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezyreachMobileApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIb1lFY5NkLMja2vnvmv4Q4Wibl2HYzyE',
    appId: '1:51581949561:web:f4368f9f4b8602fe6ca6a8',
    messagingSenderId: '51581949561',
    projectId: 'ezyreach-5fe0a',
    authDomain: 'ezyreach-5fe0a.firebaseapp.com',
    storageBucket: 'ezyreach-5fe0a.firebasestorage.app',
    measurementId: 'G-3BSS48G4GM',
  );
}
